import test from 'node:test';import assert from 'node:assert/strict';import {computeServiceMetrics,recordServiceUsage} from './src/business-metrics.js';import {adjustBillingMembership} from './src/billing-membership.js';
const t=x=>Date.parse(x+'T00:00:00Z');
const base={subscriptions:[{id:'w',customer_id:'a',product_code:'weekly',status:'canceled',billing_interval:'monthly',created_at:'2026-08-01T00:00:00Z'},{id:'i',customer_id:'a',product_code:'curriculum',status:'active',billing_interval:'monthly',created_at:'2026-09-05T00:00:00Z'}],transactions:[],usage:[],observations:[],replacements:[]};
const tx=(sub,product,date,amount=980)=>({subscription_id:sub,customer_id:'a',product_code:product,transaction_type:'recurring',status:'paid',amount_yen:amount,occurred_at:date+'T00:00:00Z'});
test('TAYORIからIROHA移行後の有料支払いを継続に含め、移行件数を別に数える',()=>{const data=computeServiceMetrics({...base,transactions:[tx('w','weekly','2026-08-10'),tx('i','curriculum','2026-09-10',2980)],replacements:[{status:'completed',completed_at:'2026-09-05T00:00:00Z'}]},t('2026-09-01'),t('2026-10-01'),t('2026-10-06'));assert.deepEqual(data[0].retention,{value:1,numerator:1,denominator:1});assert.equal(data[0].migrations,1);assert.equal(data[1].revenue.recurring_yen,2980);});
test('初回利用の7日観察待ち・計測開始前を除外し、人数で数える',()=>{const data=computeServiceMetrics({...base,measurementStart:t('2026-08-20'),subscriptions:[{...base.subscriptions[1],created_at:'2026-09-05T00:00:00Z'},{...base.subscriptions[1],id:'j',customer_id:'b',created_at:'2026-10-04T00:00:00Z'}],usage:[{customer_id:'a',product_code:'curriculum',kind:'lesson_start',occurred_at:'2026-09-06T00:00:00Z'}]},t('2026-09-01'),t('2026-10-07'),t('2026-10-06'))[1];assert.equal(data.activation.value,1);assert.equal(data.activation.denominator,1);assert.equal(data.activation_waiting,1);});
test('無料終了後の有料化は期限確認済み・7日観察済みだけ。入会金・0円を除外',()=>{const observations=[{subscription_id:'i',category:'free_coupon',free_until:'2026-09-10T00:00:00Z',observed_at:'2026-09-01T00:00:00Z'},{subscription_id:'w',free_until:'',observed_at:'2026-09-01T00:00:00Z'}];let services=computeServiceMetrics({...base,observations,transactions:[{...tx('i','curriculum','2026-09-11'),transaction_type:'entry_fee'},tx('i','curriculum','2026-09-11',0)]},t('2026-09-01'),t('2026-10-01'),t('2026-10-06'));assert.equal(services[1].free_conversion.value,0);services=computeServiceMetrics({...base,observations,transactions:[tx('i','curriculum','2026-09-12',2980)]},t('2026-09-01'),t('2026-10-01'),t('2026-10-06'));assert.equal(services[1].free_conversion.value,1);});
test('年額の翌月未請求を解約として数えない',()=>{const data=computeServiceMetrics({...base,subscriptions:base.subscriptions.map(s=>({...s,billing_interval:'annual'})),transactions:[tx('w','weekly','2026-08-10')]},t('2026-09-01'),t('2026-10-01'),t('2026-10-06'));assert.equal(data[0].retention.value,null);});
test('Stripeの現行価格から月額を照合し、解約予定も現在月額には含む',async()=>{const result=await adjustBillingMembership({kpis:{},quality:{},breakdown:[{product_code:'curriculum'}]},[{...base.subscriptions[1],provider_subscription_id:'sub_test',recurring_amount_yen:980,cancel_at_period_end:1}],{STRIPE_MODE:'live',STRIPE_SECRET_KEY:'rk_live_example',BILLING_COUPON_FETCH:async()=>new Response(JSON.stringify({id:'sub_test',livemode:true,status:'active',discounts:[],items:{data:[{price:{currency:'jpy',unit_amount:2980,recurring:{interval:'month'}}}]}}))});assert.equal(result.membership.current_paid_monthly_yen,2980);assert.equal(result.membership.recurring_monthly_yen,0);assert.ok(!JSON.stringify(result).includes('sub_test'));});
test('利用記録の障害で学習を止めず、運営確認を記録しない',async()=>{const env={DB:{prepare(){throw Error('offline');}}};await assert.doesNotReject(()=>recordServiceUsage(env,{customer:{id:'a'},access:{}},'weekly','member_open'));await assert.doesNotReject(()=>recordServiceUsage(env,{access:{staff_access:true}},'weekly','member_open'));});
import {readFileSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';import {loadWorker} from './test-support.mjs';
const worker=await loadWorker();
function apiFixture(){const sql=new DatabaseSync(':memory:');for(const f of ['schema.sql','migrations/20260911_curriculum_foundation.sql','migrations/20260920_billing_dashboard.sql','migrations/20261002_iroha_lesson_notes.sql','migrations/20261003_iroha_playback.sql','migrations/20261006_dashboard_metrics.sql'])sql.exec(readFileSync('apps/tsuzuri-studio-api/'+f,'utf8'));sql.exec("INSERT INTO members(id,email,name,role,status) VALUES('ed','editor@example.com','Editor','editor','active');");function prepare(q){let a=[];return {bind(...x){a=x;return this;},async all(){return {results:sql.prepare(q).all(...a)};},async first(){return sql.prepare(q).get(...a);},async run(){return {meta:{changes:Number(sql.prepare(q).run(...a).changes)}};}};}return {sql,env:{DB:{prepare},ALLOW_DEV_AUTH:'true',STRIPE_MODE:'test'}};}
test('チーム編集者には匿名集計のみを返し、公開member・未認証を拒否する',async()=>{const {env}=apiFixture();const request=(prefix,email)=>new Request('https://test.local'+prefix+'/api/business-summary?start=2026-10-01&end=2026-10-07',{headers:email?{'x-column-studio-dev-email':email}:{}});let response=await worker.fetch(request('/api/totonoe-studio','editor@example.com'),env);assert.equal(response.status,200);const data=await response.json();assert.equal(data.services.length,2);const body=JSON.stringify(data);for(const word of ['customer_id','subscription_id','email','display_name','provider_subscription_id'])assert.ok(!body.includes(word));assert.equal((await worker.fetch(request('/api/totonoe-member','editor@example.com'),env)).status,404);assert.equal((await worker.fetch(request('/api/totonoe-studio'),env)).status,403);});
test('利用テーブルを取得できないときは利用率を0%にしない',async()=>{const {sql,env}=apiFixture();sql.exec('DROP TABLE service_usage_events');const r=await worker.fetch(new Request('https://test.local/api/totonoe-studio/api/business-summary?start=2026-10-01&end=2026-10-07',{headers:{'x-column-studio-dev-email':'editor@example.com'}}),env);const d=await r.json();assert.equal(d.quality.coverage.member,false);assert.equal(d.services[0].activation.value,null);assert.equal(d.services[0].usage.available,false);});
test('契約解約率は期首の会員を分母にし、IROHA移行と再開を解約扱いしない',()=>{const statusEvents=[{subscription_id:'w',customer_id:'a',status:'active',effective_at:'2026-08-01T00:00:00Z'},{subscription_id:'w',customer_id:'a',status:'canceled',effective_at:'2026-09-05T00:00:00Z'}];const params=[t('2026-09-01'),t('2026-10-01'),t('2026-10-06')];let d=computeServiceMetrics({...base,statusEvents},...params);assert.equal(d[0].contract_churn.value,1);d=computeServiceMetrics({...base,statusEvents,replacements:[{source_subscription_id:'w',status:'completed',completed_at:'2026-09-05T00:00:00Z'}]},...params);assert.equal(d[0].contract_churn.value,0);d=computeServiceMetrics({...base,statusEvents:statusEvents.concat({subscription_id:'w',customer_id:'a',status:'active',effective_at:'2026-09-06T00:00:00Z'})},...params);assert.equal(d[0].contract_churn.value,0);});
