import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {collectJourney,journeySummary,recordJourneyCheckout,journeyAttribution,journeyPath} from './src/journey-analytics.js';
import {withJourneyMeasurement} from '../site-worker/journey-release.js';
import {loadWorker} from './test-support.mjs';
const worker=await loadWorker();
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('apps/tsuzuri-studio-api/migrations/20261005_journey_analytics.sql','utf8'));sql.exec(`CREATE TABLE stripe_checkout_attempts(id TEXT PRIMARY KEY,status TEXT,stripe_subscription_id TEXT,livemode INTEGER);CREATE TABLE customer_subscriptions(id TEXT PRIMARY KEY,provider_subscription_id TEXT,livemode INTEGER);CREATE TABLE billing_transactions(subscription_id TEXT,livemode INTEGER,status TEXT,amount_yen INTEGER,occurred_at TEXT,transaction_type TEXT DEFAULT 'recurring');`);const prepare=q=>{let args=[];return {bind(...a){args=a;return this;},async first(){return sql.prepare(q).get(...args)||null;},async all(){return {results:sql.prepare(q).all(...args)};},async run(){return {meta:{changes:Number(sql.prepare(q).run(...args).changes)}};}};};return {sql,DB:{prepare},PUBLIC_SITE_ORIGIN:'https://basecraftas.com',STRIPE_MODE:'live',CUSTOMER_AUTH_SECRET:'test-secret'};}
const path='/projects/totonoe/';
function req(body={},headers={}){return new Request('https://basecraftas.com/api/public/journey-event',{method:'POST',headers:{origin:'https://basecraftas.com','content-type':'application/json','user-agent':'Mozilla/5.0',...headers},body:JSON.stringify({id:crypto.randomUUID(),kind:'page_view',path,...body})});}
const tag={source:'x',content:'kanto-toshiki_post1',campaign:'totonoe_team'};
const cookie=r=>r.headers.get('set-cookie').split(';')[0];
test('内部確認・識別済みAI/BotをDBへ記録しない',async()=>{const env=fixture();for(const headers of [{cookie:'totonoe_internal=1'},{'user-agent':'ChatGPT-User'},{'user-agent':'HeadlessChrome'},{'user-agent':'Googlebot'}])assert.deepEqual(await (await collectJourney(req({},headers),env)).json(),{excluded:true});assert.equal(env.sql.prepare('SELECT COUNT(*) AS n FROM journey_sessions').get().n,0);});
test('正規Origin・イベント・公開ページだけを受け付ける',async()=>{const env=fixture();assert.equal((await collectJourney(req({}, {origin:'https://evil.example'}),env)).status,403);for(const p of ['/projects/totonoe/TAYORI/login.html','/projects/totonoe/IROHA/lesson.html','/apps/totonoe-studio/','/projects/totonoe/?email=secret'])assert.equal((await collectJourney(req({path:p}),env)).status,400);assert.equal((await collectJourney(req({kind:'unknown'}),env)).status,400);assert.equal(journeyPath('/projects/totonoe/TAYORI/subscribe.html'),'/projects/totonoe/TAYORI/subscribe.html');assert.equal(journeyAttribution({...tag,campaign:'other'}).owner,'');assert.equal(journeyAttribution({...tag,content:'email@example.com'}).owner,'');});
test('タグ付き入口からタグなし内部遷移の帰属を維持し、再送を二重計上しない',async()=>{const env=fixture(),id=crypto.randomUUID();const first=await collectJourney(req({id,attribution:tag}),env);const h={cookie:cookie(first)};await collectJourney(req({path:'/projects/totonoe/tayori'},h),env);await collectJourney(req({kind:'cta_click',target:'/projects/totonoe/TAYORI/subscribe.html'},h),env);await collectJourney(req({id,attribution:tag}),env);assert.equal(env.sql.prepare('SELECT COUNT(*) AS n FROM journey_sessions').get().n,1);assert.equal(env.sql.prepare('SELECT COUNT(*) AS n FROM journey_events').get().n,3);const s=env.sql.prepare('SELECT * FROM journey_sessions').get();assert.equal(s.owner,'kanto-toshiki');assert.equal(s.source,'x');await collectJourney(req({attribution:{...tag,source:'instagram'}},h),env);assert.equal(env.sql.prepare('SELECT COUNT(*) AS n FROM journey_sessions').get().n,2);});
test('入口別の経路・契約・後日の有料支払いを集計し、0円・テスト決済を分ける',async()=>{const env=fixture();env.sql.prepare('UPDATE journey_config SET started_at=?').run('2026-10-01T00:00:00.000Z');const first=await collectJourney(req({attribution:tag}),env),h={cookie:cookie(first)};await collectJourney(req({path:'/projects/totonoe/tayori'},h),env);await collectJourney(req({kind:'cta_click',target:'/projects/totonoe/TAYORI/subscribe.html'},h),env);const id=env.sql.prepare('SELECT id FROM journey_sessions').get().id;env.sql.prepare('UPDATE journey_sessions SET started_at=?').run('2026-10-02T16:00:00.000Z');env.sql.prepare('UPDATE journey_events SET occurred_at=?').run('2026-10-02T16:01:00.000Z');env.sql.exec("INSERT INTO stripe_checkout_attempts VALUES('attempt','completed','sub_live',1),('test','completed','sub_test',0);INSERT INTO customer_subscriptions VALUES('cs','sub_live',1);INSERT INTO billing_transactions(subscription_id,livemode,status,amount_yen,occurred_at) VALUES('cs',1,'paid',0,'2026-10-03T00:00:00Z');");await recordJourneyCheckout(req({},h),env,'attempt');await recordJourneyCheckout(req({},h),env,'test');const summary=()=>journeySummary(new Request('https://basecraftas.com/api/analytics-summary?start=2026-10-03&end=2026-10-03'),env).then(r=>r.json());let data=await summary();assert.equal(data.kpis.visits,1);assert.equal(data.links[0].completed_sessions,1);assert.equal(data.links[0].paid_sessions,0);assert.equal(data.links[0].cta_sessions,1);assert.equal(data.journeys.length,1);env.sql.exec("INSERT INTO billing_transactions(subscription_id,livemode,status,amount_yen,occurred_at) VALUES('cs',1,'paid',500,'2026-10-04T00:00:00Z');");data=await summary();assert.equal(data.links[0].paid_sessions,1);assert.equal(data.links[0].paths[0].paid_sessions,1);assert.equal(data.links[0].checkout_sessions,1);const text=JSON.stringify(data);assert.ok(!text.includes(id));assert.ok(!text.includes('sub_live'));assert.ok(!text.includes('customer_id'));});
test('集計開始前の訪問を除外し、期間上限を守る',async()=>{const env=fixture();env.sql.exec("INSERT INTO journey_sessions VALUES('historic','direct','','','/projects/totonoe/','2026-09-01T00:00:00Z','2026-09-01T00:00:00Z');");const r=await journeySummary(new Request('https://basecraftas.com/api/analytics-summary?start=2026-09-01&end=2026-10-05'),env);assert.equal((await r.json()).kpis.visits,0);assert.equal((await journeySummary(new Request('https://basecraftas.com/api/analytics-summary?start=2026-01-01&end=2026-10-05'),env)).status,400);});
test('匿名集計にもStudioログインが必要',async()=>{const env=fixture();env.sql.exec('CREATE TABLE members(id TEXT,email TEXT,name TEXT,role TEXT,status TEXT);');const r=await worker.fetch(new Request('https://basecraftas.com/api/tsuzuri-studio/api/analytics-summary'),env);assert.equal(r.status,403);});
test('Studioで内部Cookieを付け、内部閲覧とBotには計測JSを配信しない',async()=>{const previous={fetch:async()=>new Response('<html><head></head><body class="site"><script src="https://www.googletagmanager.com/gtag/js?id=G-1SK6NEFC8V"></script></body></html>',{headers:{'content-type':'text/html'}})};const release=withJourneyMeasurement(previous,'TRACK','DASH');let r=await release.fetch(new Request('https://basecraftas.com/apps/totonoe-studio/'),{},{});assert.match(r.headers.get('set-cookie'),/totonoe_internal=1/);assert.match(await r.text(),/journey-dashboard/);r=await release.fetch(new Request('https://basecraftas.com/projects/totonoe/?analytics=off'),{},{});assert.match(r.headers.get('set-cookie'),/totonoe_internal=1/);const html=await r.text();assert.match(html,/内部確認用/);assert.ok(!html.includes('googletagmanager'));assert.ok(!html.includes('journey-tracking'));r=await release.fetch(new Request('https://basecraftas.com/projects/totonoe/journey-tracking.js',{headers:{cookie:'totonoe_internal=1'}}),{},{});assert.equal(await r.text(),'');r=await release.fetch(new Request('https://basecraftas.com/projects/totonoe/'),{},{});assert.match(await r.text(),/journey-tracking/);});
test('公開memberルートで計測を受け付け、Studio集計を公開ルートに漏らさない',async()=>{const env=fixture();const original=req({attribution:tag});let r=await worker.fetch(new Request('https://basecraftas.com/api/totonoe-member/api/public/journey-event',original),env);assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/totonoe_journey=/);assert.equal(env.sql.prepare('SELECT COUNT(*) AS n FROM journey_sessions').get().n,1);r=await worker.fetch(new Request('https://basecraftas.com/api/totonoe-member/api/analytics-summary'),env);assert.equal(r.status,404);});
test('計測DBの障害は決済を止めない',async()=>{await assert.doesNotReject(()=>recordJourneyCheckout(req({},{cookie:'totonoe_journey='+crypto.randomUUID()}),{DB:{prepare(){throw Error('unavailable');}}},'attempt'));});
test('リンクの14日有料化は観察済み訪問だけを分母にし、入会金と遅い課金を除く',async context=>{context.mock.timers.enable({apis:['Date'],now:new Date('2026-10-20T00:00:00Z')});const env=fixture();env.sql.exec("UPDATE journey_config SET started_at='2026-10-01T00:00:00Z'");const first=await collectJourney(req({attribution:tag}),env),h={cookie:cookie(first)};env.sql.exec("UPDATE journey_sessions SET started_at='2026-10-01T00:00:00Z';INSERT INTO stripe_checkout_attempts VALUES('attempt','completed','sub_live',1);INSERT INTO customer_subscriptions VALUES('cs','sub_live',1);INSERT INTO billing_transactions VALUES('cs',1,'paid',5000,'2026-10-02T00:00:00Z','entry_fee');");await recordJourneyCheckout(req({},h),env,'attempt');const summary=()=>journeySummary(new Request('https://basecraftas.com/api/analytics-summary?start=2026-10-01&end=2026-10-01'),env).then(r=>r.json());let data=await summary();assert.equal(data.links[0].paid_sessions,1);assert.equal(data.links[0].recurring_sessions,0);assert.equal(data.links[0].matured_visits,1);env.sql.exec("INSERT INTO billing_transactions VALUES('cs',1,'paid',980,'2026-10-16T00:00:00Z','recurring')");data=await summary();assert.equal(data.links[0].recurring_sessions,1);assert.equal(data.links[0].matured_paid14_sessions,0);env.sql.exec("INSERT INTO billing_transactions VALUES('cs',1,'paid',980,'2026-10-05T00:00:00Z','recurring')");data=await summary();assert.equal(data.links[0].matured_paid14_sessions,1);});
